apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.networking.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: gameport
      port: {{ .Values.GamePort | int }}
      targetPort: {{ .Values.GamePort | int }}
      protocol: UDP

      nodePort: {{ default "" .Values.networking.nodePort }}

    - name: queryport
      port: {{ .Values.QueryPort | int }}
      targetPort: {{ .Values.QueryPort | int }}
      protocol: UDP

      nodePort: {{ default "" (.Values.networking.nodePort | int | add 1) }}

