{{- if .Values.AdminSettings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "abf-k8s.fullname" . }}-admin-settings
data:
  AdminSettings.ini: |
{{- if .Values.AdminSettings.Moderators }}
    [Moderators]
{{- range .Values.AdminSettings.Moderators }}
    Moderator={{ . }}
{{- end }}
{{- end }}

{{- if .Values.AdminSettings.BannedPlayers }}
    [BannedPlayers]
{{- range .Values.AdminSettings.BannedPlayers }}
    BannedPlayer={{ . }}
{{- end }}
{{- end }}
{{- end }}
