apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if eq .Values.storage.kind "hostvol" }}
        - name: gamefiles
          hostPath:
            path: {{ .Values.storage.hostvol.path }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if eq .Values.storage.kind "persistentVolumeClaim" }}
        - name: gamefiles
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-gamefiles
        {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Release.Name }}
          env:
            - name: MaxServerPlayers
              value: "{{ .Values.MaxServerPlayers }}"
            - name: Port
              value: "{{ .Values.GamePort }}"
            - name: QueryPort
              value: "{{ .Values.QueryPort }}"
            - name: ServerPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: serverPassword
            - name: SteamServerName
              value: "{{ .Values.SteamServerName }}"
            - name: NoAsyncLoadingThread
              value: "{{ .Values.NoAsyncLoadingThread }}"
            - name: WorldSaveName
              value: "{{ .Values.WorldSaveName }}"
            - name: AutoUpdate
              value: "{{ .Values.AutoUpdate }}"
            - name: UsePerfThreads
              value: "{{ .Values.UsePerfThreads }}"
            {{- range $key, $value := .Values.AdditionalEnvironmentVariables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.GamePort }}
              name: gameport
            - containerPort: {{ .Values.QueryPort }}
              name: queryport
          volumeMounts:
            - mountPath: /server
              name: gamefiles
