apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "abf-k8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if eq .Values.storage.kind "hostvol" }}
        - name: gamefiles
          hostPath:
            path: {{ .Values.storage.hostvol.path }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if eq .Values.storage.kind "persistentVolumeClaim" }}
        - name: gamefiles
          persistentVolumeClaim:
            claimName: {{ include "abf-k8s.fullname" . }}-gamefiles
        {{- end }}
        {{- if .Values.SandboxSettings }}
        - name: {{ include "abf-k8s.fullname" . }}-sandbox-settings
          configMap:
            name: {{ include "abf-k8s.fullname" . }}-sandbox-settings
        {{- end }}
        {{- if .Values.AdminSettings }}
        - name: {{ include "abf-k8s.fullname" . }}-admin-settings
          configMap:
            name: {{ include "abf-k8s.fullname" . }}-admin-settings
        {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Release.Name }}
          env:
            - name: MaxServerPlayers
              value: "{{ .Values.MaxServerPlayers }}"
            - name: Port
              value: "{{ .Values.GamePort }}"
            - name: QueryPort
              value: "{{ .Values.QueryPort }}"
            - name: ServerPassword
              valueFrom:
                secretKeyRef:
                  name: {{ include "abf-k8s.fullname" . }}-secret
                  key: serverPassword
            - name: SteamServerName
              value: "{{ .Values.SteamServerName }}"
            - name: NoAsyncLoadingThread
              value: "{{ .Values.NoAsyncLoadingThread }}"
            - name: WorldSaveName
              value: "{{ .Values.WorldSaveName }}"
            - name: AutoUpdate
              value: "{{ .Values.AutoUpdate }}"
            - name: UsePerfThreads
              value: "{{ .Values.UsePerfThreads }}"
            {{- range $key, $value := .Values.AdditionalEnvironmentVariables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: AdditionalArgs
              value: "{{- $adds := .Values.AdditionalArgs | default "" -}}
                {{- if .Values.SandboxSettings }}
                  {{- $adds = printf "%s -SandboxIniPath=Config/WindowsServer/SandboxSettings.ini" $adds }}
                {{- end }}
                {{- if .Values.AdminSettings }}
                  {{- $adds = printf "%s -AdminIniPath=Config/WindowsServer/AdminSettings.ini" $adds }}
                {{- end }}
                {{- trim $adds }}"
          resources: {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.GamePort }}
              name: gameport
            - containerPort: {{ .Values.QueryPort }}
              name: queryport
          volumeMounts:
            - mountPath: /server
              name: gamefiles
          {{- if .Values.SandboxSettings }}
            - name: {{ include "abf-k8s.fullname" . }}-sandbox-settings
              mountPath: /server/AbioticFactor/Saved/Config/WindowsServer/SandboxSettings.ini
              subPath: SandboxSettings.ini
          {{- end }}
          {{- if .Values.AdminSettings }}
            - name: {{ include "abf-k8s.fullname" . }}-admin-settings
              mountPath: /server/AbioticFactor/Saved/Config/WindowsServer/AdminSettings.ini
              subPath: AdminSettings.ini
          {{- end }}
