{{ if eq .Values.storage.kind "persistentVolumeClaim" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "project-zomboid-k8s.fullname" . }}-gamefiles
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.storage.pvc.storageClassName }}
  storageClassName: {{ .Values.storage.pvc.gamefiles.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pvc.gamefiles.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "project-zomboid-k8s.fullname" . }}-configfiles
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.storage.pvc.storageClassName }}
  storageClassName: {{ .Values.storage.pvc.configfiles.storageClassName }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pvc.configfiles.size }}
{{ end }}
