apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-zomboid-k8s.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  serverPassword: {{ .Values.SERVER_PASSWORD | b64enc | quote }}
  adminPassword: {{ .Values.ADMIN_PASSWORD | b64enc | quote }}
  rconPassword: {{ .Values.RCON_PASSWORD | b64enc | quote }}
