apiVersion: v1
kind: Service
metadata:
  name: {{ include "planar-ally-k8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.networking.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: webport
      port: {{ .Values.networking.port | int }}
      targetPort: 8000
      protocol: TCP
      {{- if .Values.networking.nodePort }}
      nodePort: {{ default "" .Values.networking.nodePort }}
      {{- end }}
