apiVersion: v1
kind: Service
metadata:
  name: abiotic-factor-server
  namespace: abf-k8s
spec:
  ports:
    - name: gameport
      port: 7777
      targetPort: 7777
      protocol: UDP

    - name: queryport
      port: 27015
      targetPort: 27015
      protocol: UDP

  type: NodePort
  selector:
    app: abiotic-factor-server
