image:
  repository: ghcr.io/pleut/abiotic-factor-linux-docker
  tag: latest

nodeSelector: {}

MaxServerPlayers: "6"
GamePort: 30000
QueryPort: 30001
ServerPassword: changeme
SteamServerName: "ABF K8s"
NoAsyncLoadingThread: "true"
WorldSaveName: "Cascade"
AutoUpdate: "true"
UsePerfThreads: "true"
AdditionalEnvironmentVariables: {}

resources:
  limits:
    memory: 4Gi
    cpu: "1"

storage:
  kind: hostvol
  hostvol:
    path: /data/abf
  pvc:
    size: 5Gi
    storageClassName: false

networking:
  type: LoadBalancer
  publishQueryPort: true
  nodePort: 30000
