name: abf-k8s
image:
  repository: ghcr.io/pleut/abiotic-factor-linux-docker
  tag: latest
imagePullPolicy: Always

nodeSelector: {}

MaxServerPlayers: "6"
GamePort: 7777
QueryPort: 27015
ServerPassword: changeme
SteamServerName: "Kuberts Abiotic Factor Server"
NoAsyncLoadingThread: "true"
WorldSaveName: "Cascade"
AutoUpdate: "true"
UsePerfThreads: "true"
AdditionalEnvironmentVariables: {}

resources:
  limits:
    memory: 2Gi
    cpu: "1"

storage:
  kind: hostvol
  hostvol:
    path: /data/abf
  pvc:
    size: 5Gi
    storageClassName: false

networking:
  type: LoadBalancer
  publishQueryPort: true
# nodePort: 30000

# SandboxSettings: {}
# AdminSettings: {}
